#!/bin/bash
# Purge generated / runtime artifacts so the working tree stays clean
# (repo-structure-17: one documented, gitignored runtime set). Safe to run
# anytime — it only removes regenerable output, never source or config.
#
# Usage:  bash scripts/clean-workspace.sh [--dry-run]
#
# The directories/files below are all gitignored; this simply reclaims disk and
# keeps `git status` readable. `.archive/` is intentionally NOT purged (it is
# local retirement storage).
set -uo pipefail

cd "$(git rev-parse --show-toplevel 2>/dev/null || echo .)" || exit 1

DRY_RUN=0
[ "${1:-}" = "--dry-run" ] && DRY_RUN=1

# Runtime/generated directories (contents removed, directory kept if present).
RUNTIME_DIRS=(
    logs output clusters reports import telemetry
    build dist test_output tracer-output test-results
    .pytest_cache htmlcov
)

# Stray root artifacts (regenerated by tools).
STRAY_FILES=(
    .coverage coverage.xml .DS_Store app.log web_app.log
)

purge() {
    local target="$1"
    [ -e "$target" ] || return 0
    if [ "$DRY_RUN" -eq 1 ]; then
        echo "would remove: $target"
    else
        rm -rf "$target"
        echo "removed: $target"
    fi
}

echo "=== clean-workspace ${DRY_RUN:+(dry-run)} ==="
for d in "${RUNTIME_DIRS[@]}"; do
    if [ -d "$d" ]; then
        # Remove contents but keep the directory so tools can re-create files.
        for item in "$d"/* "$d"/.[!.]*; do
            [ -e "$item" ] && purge "$item"
        done
    fi
done
for f in "${STRAY_FILES[@]}"; do
    purge "$f"
done
# Stray compiled Python / OS cruft anywhere in the tree.
find . -type d -name __pycache__ -not -path './.git/*' -print0 2>/dev/null | while IFS= read -r -d '' p; do
    purge "$p"
done

echo "=== done ==="
